/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-12-31 11:27:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.share.users;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/view/share/include/imgback.jsp", Long.valueOf(1449803209687L));
    _jspx_dependants.put("/view/share/include/bottom2.jsp", Long.valueOf(1449803209670L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>读者注册</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t \tfunction check()\r\n");
      out.write("\t {\r\n");
      out.write("\t var user_name = document.getElementById(\"user_name\").value;\r\n");
      out.write("\t var user_age = document.getElementById(\"tuser_age\").value;\r\n");
      out.write("\t var user_password1 = document.getElementById(\"user_password1\").value;\r\n");
      out.write("\t var user_password2 = document.getElementById(\"user_password2\").value;\r\n");
      out.write("\t  if(user_name==\"\")\r\n");
      out.write("\t {\r\n");
      out.write("\t document.getElementById(\"err\").innerHTML=\"用户名不能为空\";\r\n");
      out.write("\t }\r\n");
      out.write("\t else  if(user_age==\"\")\r\n");
      out.write("\t {\r\n");
      out.write("\t document.getElementById(\"err\").innerHTML=\"年龄不能为空\";\r\n");
      out.write("\t }\r\n");
      out.write("\t else if(user_password1==\"\" || user_password2==\"\")\r\n");
      out.write("\t {\r\n");
      out.write("\t document.getElementById(\"err\").innerHTML=\"密码不能为空\";\r\n");
      out.write("\t }\r\n");
      out.write("\t else if(user_password1!=user_password2)\r\n");
      out.write("\t {\r\n");
      out.write("\t document.getElementById(\"err\").innerHTML=\"两次密码输入不一致\";\r\n");
      out.write("\t }\r\n");
      out.write("\t else document.getElementById(\"myform\").submit();\r\n");
      out.write("\t } \r\n");
      out.write("\r\n");
      out.write("\tvar xmlHttp = null;\r\n");
      out.write("\tfunction createXMLHttpRequest() {\r\n");
      out.write("\t\tif (window.XMLHttpRequest) { //检测是否为Mozilla浏览器\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\txmlHttp = new XMLHttpRequest();\r\n");
      out.write("\t\t\t} \r\n");
      out.write("\t\t\tcatch (e) {\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if (window.ActiveXObject) { //检测是否为IE浏览器\r\n");
      out.write("\t\t\ttry {\r\n");
      out.write("\t\t\t\txmlHttp = new ActiveXObject(\"Msxml2.XMLHTTP\");\r\n");
      out.write("\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\ttry {\r\n");
      out.write("\t\t\t\t\txmlHttp = new ActiveXObject(\"Microsoft.XMLHTTP\");\r\n");
      out.write("\t\t\t\t} catch (e) {\r\n");
      out.write("\t\t\t\t\talert(\"不支持ajax\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction validatee() {\r\n");
      out.write("\t\tvar user_name = document.getElementById(\"user_name\").value;\r\n");
      out.write("\t\tif (user_name != \"\") {\r\n");
      out.write("\t\t\t//this   field    trim(field.value).length!=0     trim(field.value)\r\n");
      out.write("\t\t\t//创建Ajax核心对象XMLHttpRequest  \r\n");
      out.write("\t\t\tcreateXMLHttpRequest();\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(request.getContextPath());
      out.write("/UserServlet?userFlag=find&ccc=\"+user_name;\r\n");
      out.write("\t\t\t//设置请求方式为get,请求的URL,异步提交  \r\n");
      out.write("\t\t\txmlHttp.open(\"GET\", url, true);\r\n");
      out.write("\t\t\t//将方法地址赋值给onreadystatechange属性  \r\n");
      out.write("\t\t\txmlHttp.onreadystatechange = callback;\r\n");
      out.write("\t\t\txmlHttp.send();\r\n");
      out.write("\t\t} /* else {\r\n");
      out.write("\t\t\tdocument.getElementById(\"spanUserId\").innerHTML = \"用户名不能为空\";\r\n");
      out.write("\t\t\tvar btn = document.getElementById(\"btn\");\r\n");
      out.write("\t     \tbtn.disabled=\"true\";\r\n");
      out.write("\t\t} */\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction callback() {\r\n");
      out.write("\t\t//4表示有响应  \r\n");
      out.write("\t\tif (xmlHttp.readyState == 4) {\r\n");
      out.write("\t\t\t//200表示请求成功  \r\n");
      out.write("\t\t\tif (xmlHttp.status == 200) {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"spanUserId\").innerHTML =  xmlHttp.responseText;\r\n");
      out.write("\t\t\t\tvar btn = document.getElementById(\"btn\");\r\n");
      out.write("\t\t     \tbtn.disabled=\"true\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}  /* else {\r\n");
      out.write("\t\t\t\tdocument.getElementById(\"spanUserId\").innerHTML = \"用户名必须唯一\";\r\n");
      out.write("\t\t\t}  */\r\n");
      out.write("\t\t}/*  else {\r\n");
      out.write("\t\t\talert(\"请求失败,错误码=\" + xmlHttp.status);\r\n");
      out.write("\t\t} */\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction again()\r\n");
      out.write("\t{\r\n");
      out.write("\t\tvar btn = document.getElementById(\"btn\");\r\n");
      out.write("     \tbtn.removeAttribute(\"disabled\");\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"main index\"\r\n");
      out.write("\tstyle=\"padding-top: 60px; width: 960px; height: 100%; min-height: 480px; margin: 0 auto; font-size: 14px;\">\r\n");
      out.write("\t\t<div style=\"margin: 60px 0 0 0;\">\r\n");
      out.write("\t\t\t<div style=\"float: left; width: 400px;\">");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 40px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\"> <img\r\n");
      out.write("\t\talt=\"图片加载失败~~点此返回主页\" src=\"");
      out.print(request.getContextPath());
      out.write("/img/book.jpg\"\r\n");
      out.write("\t\twidth=\"200px\" height=\"160px\" />\r\n");
      out.write("</a>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</div>\r\n");
      out.write("\t\t\t<div class=\"content\"\r\n");
      out.write("\t\t\tstyle=\"width: 560px; float: left; margin: 60px 0 0 0;\">\r\n");
      out.write("\t\t\t\t<form id=\"myform\"\r\n");
      out.write("\t\t\t\taction=\"");
      out.print(request.getContextPath());
      out.write("/UserServlet?userFlag=save\"\r\n");
      out.write("\t\t\t\tmethod=\"post\">\r\n");
      out.write("\t\t\t\t\t<table cellpadding=\"5px\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th width=\"100\">用户名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"user_name\" type=\"text\" id=\"user_name\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonblur=\"validatee()\" onfocus=\"again()\">*</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>性别</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><select name=\"usersex\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"男\" selected=\"selected\">男</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"女\">女</option>\r\n");
      out.write("\t\t\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>年龄</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"tuserage\" type=\"text\" id=\"tuser_age\">*</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>密码</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"userpassword1\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"user_password1\">*</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>重复密码</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"userpassword2\" type=\"password\"\r\n");
      out.write("\t\t\t\t\t\t\t\tid=\"user_password2\">*</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>个性签名</th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input name=\"userintro\" type=\"text\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th><a href=\"\">读者注册协议</a></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td><input id=\"btn\" type=\"button\" onclick=\"check()\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"同意并注册\"></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"err\">带*的不能为空</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t\t\t\t<td id=\"spanUserId\">用户名必须唯一</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\t<div style=\"clear: float; clear: both;\"></div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- \r\n");
      out.write("margin:-24px 0 0 0;\r\n");
      out.write(" -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#footer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"footer\"\r\n");
      out.write("\tstyle=\"height: 88px; background-color: #F3F3F3; border-top: 2px solid #CCCCCC; z-index: 9999; box-shadow: 0 0 5px #999999;\">\r\n");
      out.write("\t\t<div style=\"text-align: center; margin: 20px 0 0 0; font-size: 15px;\">\r\n");
      out.write("\t\t\t@版权所有 2015-2015 灵彡阁 <a target=\"_blank\"\r\n");
      out.write("\t\t\thref=\"http://user.qzone.qq.com/877048930/334\">联系我们</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
