/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2015-12-31 11:33:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.view.share.admindo;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.sql.Time;

public final class returndo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/view/share/include/bottom2.jsp", Long.valueOf(1449803209670L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.sql.Time");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.sql.Date");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>还书</title>\r\n");
      out.write("</head>\r\n");

	String time = new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime());

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("table {\r\n");
      out.write("\tmargin-top: 130px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t function check()\r\n");
      out.write("\t {\r\n");
      out.write("\t\t var book_name = document.getElementById(\"book_name\").value;\r\n");
      out.write("\t\t var lend_user = document.getElementById(\"lend_user\").value;\r\n");
      out.write("\t\t if(book_name==\"\")\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t document.getElementById(\"err\").innerHTML=\"书名不能为空\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t else if(lend_user==\"\")\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\t document.getElementById(\"err\").innerHTML=\"用户名不能为空\";\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t else document.getElementById(\"myform\").submit();\r\n");
      out.write("\t }\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<form id=\"myform\"\r\n");
      out.write("\taction=\"");
      out.print(request.getContextPath());
      out.write("/BorrowServlet?borrowservlet=returning&returndatee=");
      out.print(time );
      out.write("\"\r\n");
      out.write("\tmethod=\"post\">\r\n");
      out.write("\t\t<table align=\"center\" cellpadding=\"10px\">\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th valign=\"top\">借阅书名</th>\r\n");
      out.write("\t\t\t\t<td><input id=\"book_name\" type=\"text\" name=\"bookname\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th valign=\"top\">借阅读者</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" id=\"lend_user\" name=\"lenduser\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th valign=\"top\">归还日期</th>\r\n");
      out.write("\t\t\t\t<td><input type=\"text\" value=\"");
      out.print(time );
      out.write("\" disabled=\"true\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>归还数量</th>\r\n");
      out.write("\t\t\t\t<td><select id=\"number\" name=\"number\">\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">1</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">2</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"3\">3</option>\r\n");
      out.write("\t\t\t\t</select></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t<td><input type=\"checkbox\" value=\"y\" name=\"credit\">是否违约</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td><input type=\"button\" value=\"确认归还\" onclick=\"check()\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t\t<td><a href=\"");
      out.print(request.getContextPath());
      out.write("/view/share/admin/admindo.jsp\">返回功能页面</a></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th></th>\r\n");
      out.write("\t\t\t\t<td id=\"err\"></td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("</form>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- \r\n");
      out.write("margin:-24px 0 0 0;\r\n");
      out.write(" -->\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("#footer {\r\n");
      out.write("\tposition: absolute;\r\n");
      out.write("\tbottom: 0px;\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id=\"footer\"\r\n");
      out.write("\tstyle=\"height: 88px; background-color: #F3F3F3; border-top: 2px solid #CCCCCC; z-index: 9999; box-shadow: 0 0 5px #999999;\">\r\n");
      out.write("\t\t<div style=\"text-align: center; margin: 20px 0 0 0; font-size: 15px;\">\r\n");
      out.write("\t\t\t@版权所有 2015-2015 灵彡阁 <a target=\"_blank\"\r\n");
      out.write("\t\t\thref=\"http://user.qzone.qq.com/877048930/334\">联系我们</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
